on:
  push: 
    branches:
      - rollback
  pull_request:
    branches:    
        - main        
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get lasted code
      uses: actions/checkout@v3

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with: 
        server: emilsb5.sg-host.com
        username: ${{ secrets.ftp_username}}
        password: ${{ secrets.ftp_password}}
        server-dir: /emilsb5.sg-host.com/public_html/